--[[
           _______________________________________________
  ________|        Power AntiCheat  v2.6                 |_______
  \       |        Developed by Yolo#5921                |      /
   \      |        Discord: discord.gg/zyuuEgR7ZR        |     /
   /      |______________________________________________|     \
  /__________)                                        (_________\

]]--


PowerAC_Table = {

	ExplosionsSilentBan = true,

	ExplosionsInvisibleBan = true,

	ExplosionsNodamageScaleBan = true,

	ExplosionsList = {

		{	id = 0, 	name = "Grenade", 				log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 1, 	name = "GrenadeLauncher", 		log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 2, 	name = "PipeBoomb", 			log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 3, 	name = "PipeBoomb", 			log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 4, 	name = "Molotov", 				log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 5, 	name = "TankShell", 			log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 6, 	name = "Hi_Octane", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 7, 	name = "Car", 					log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 8, 	name = "Plance", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 9, 	name = "PetrolPump", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 10 },
		{	id = 10, 	name = "Bike", 					log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 11, 	name = "Dir_Steam", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 12, 	name = "Dir_Flame", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 2 },
		{	id = 13, 	name = "Dir_Water_Hydrant", 	log = true, ban = false , 	cancelevent = true, checkbypass = true, maxexplosion = 6 },
		{	id = 14, 	name = "Dir_Gas_Canister", 		log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 6 },
		{	id = 15, 	name = "Boat", 					log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 16, 	name = "Ship_Destroy", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 17, 	name = "Truck", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 18, 	name = "Bullet", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 19, 	name = "SmokeGrenadeLauncher",	log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 20, 	name = "SmokeGrenade", 			log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 21, 	name = "BZGAS", 				log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 22, 	name = "Flare", 				log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 23, 	name = "Gas_Canister", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 24, 	name = "Extinguisher",			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 25, 	name = "Programmablear", 		log = true, ban = false,	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 26, 	name = "Train", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 27, 	name = "Barrel", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 28, 	name = "PROPANE", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 29, 	name = "Blimp", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 2 },
		{	id = 30, 	name = "Dir_Flame_Explode", 	log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 31, 	name = "Tanker", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 2 },
		{	id = 32, 	name = "PlaneRocket", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 32, 	name = "PlaneRocket", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 34, 	name = "Gas_Tank", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 33, 	name = "VehicleBullet", 		log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 35, 	name = "FireWork", 				log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 36, 	name = "SnowBall", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 37, 	name = "ProxMine", 				log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 38, 	name = "Valkyrie_Cannon", 		log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
	},

	AntiSpawnMassEntity = true,

	MaxVehicleSpowned = 10, 

	MaxPedSpowned = 10,
	
	BlacklistedEntityCreating = {
		    --Props
			"prop_container_01b",
			"prop_container_01g",
			"prop_container_01a",
			"prop_container_01e",
			"prop_container_01h",
			"prop_container_01mb",
			"prop_container_01c",
			"prop_container_ld_d",
			"prop_container_02a",
			"prop_container_01d",
			"prop_ld_container",
			"prop_container_hole",
			"prop_container_05a",
			"stt_prop_stunt_bowling_ball",
			"prop_fnclink_05crnr1",
			"xs_prop_hamburgher_wl",
			"xs_prop_plastic_bottle_wl",
			"prop_windmill_01",
			"p_spinning_anus_s",
			"stt_prop_ramp_adj_flip_m",
			"stt_prop_ramp_adj_flip_mb",
			"stt_prop_ramp_adj_flip_s",
			"stt_prop_ramp_adj_flip_sb",
			"stt_prop_ramp_adj_hloop",
			"stt_prop_ramp_adj_loop",
			"stt_prop_ramp_jump_l",
			"stt_prop_ramp_jump_m",
			"stt_prop_ramp_jump_s",
			"stt_prop_ramp_jump_xl",
			"stt_prop_ramp_jump_xs",
			"stt_prop_ramp_jump_xxl",
			"stt_prop_ramp_multi_loop_rb",
			"stt_prop_ramp_spiral_l",
			"stt_prop_ramp_spiral_l_l",
			"stt_prop_ramp_spiral_l_m",
			"stt_prop_ramp_spiral_l_s",
			"stt_prop_ramp_spiral_l_xxl",
			"stt_prop_ramp_spiral_m",
			"stt_prop_ramp_spiral_s",
			"stt_prop_ramp_spiral_xxl",
			"stt_prop_stunt_track_dwslope45",
			"stt_prop_stunt_track_dwslope30",
			"stt_prop_stunt_track_dwslope15",
			"stt_prop_stunt_soccer_ball",
			"prop_beach_fire",
			"sr_prop_spec_tube_xxs_01a",
			"prop_container_03b",
			"stt_prop_stunt_ramp",
			"stt_prop_stunt_wideramp",
			"prop_poster_tube_02",
			"prop_poster_tube_01",
			"prop_cs_pour_tube",
			"p_cs_pour_tube_s",
			"stt_prop_stunt_tube_crn",
			"stt_prop_stunt_tube_crn2",
			"stt_prop_stunt_tube_crn_15d",
			"stt_prop_stunt_tube_crn_30d",
			"stt_prop_stunt_tube_crn_30d",
			"stt_prop_stunt_tube_cross",
			"stt_prop_stunt_tube_end",
			"stt_prop_stunt_tube_ent",
			"stt_prop_stunt_tube_fn_01",
			"stt_prop_stunt_tube_fn_02",
			"stt_prop_stunt_tube_fn_04",
			"stt_prop_stunt_tube_fn_05",
			"stt_prop_stunt_tube_fork",
			"stt_prop_stunt_tube_jmp2",
			"stt_prop_stunt_tube_l",
			"stt_prop_stunt_tube_m",
			"stt_prop_stunt_tube_qg",
			"stt_prop_stunt_tube_s",
			"stt_prop_stunt_tube_xs",
			"stt_prop_track_tube_02",
			"stt_prop_stunt_bblock_huge_01",
			"stt_prop_stunt_bblock_huge_02",
			"stt_prop_stunt_bblock_huge_04",
			"stt_prop_stunt_bblock_huge_03",
			"stt_prop_stunt_bblock_huge_05",
			"stt_prop_stunt_bblock_hump_01",
			"stt_prop_stunt_bblock_lrg1",
			"stt_prop_stunt_bblock_qp",
			"stt_prop_stunt_bblock_qp3",
			"stt_prop_stunt_bblock_qp2",
			"stt_prop_stunt_bblock_xl3",
			"stt_prop_stunt_bblock_xl1",
			"stt_prop_stunt_bowling_pin",
			"stt_prop_stunt_jump15",
			"stt_prop_stunt_jump30",
			"stt_prop_stunt_jump45",
			"stt_prop_stunt_jump_l",
			"stt_prop_stunt_landing_zone_01",
			"stt_prop_stunt_soccer_lball",
			"stt_prop_stunt_soccer_sball",
			"stt_prop_stunt_track_cutout",
			"stt_prop_stunt_track_bumps",
			"stt_prop_stunt_track_dwuturn",
			"stt_prop_stunt_track_jump",
			"stt_prop_stunt_track_otake",
			"stt_prop_stunt_track_slope15",
			"stt_prop_stunt_track_slope30",
			"stt_prop_stunt_track_st_01",
			"stt_prop_stunt_track_st_02",
			"stt_prop_stunt_track_start_02",
			"stt_prop_stunt_track_uturn",
			"hei_prop_carrier_radar_1",
			"hei_prop_carrier_defense_02",
			"hei_prop_mini_sever_02",
			"hei_prop_ss1_mpint_door_l",
			"lts_prop_lts_elecbox_24",
			"lts_prop_lts_elecbox_24b",
			"p_armchair_01_s",
			"p_beefsplitter_s",
			"p_cablecar_s",
			"p_crahsed_heli_s",
			"p_cs_mp_jet_01_s",
			"p_gate_prison_01_s",
			"vp_ld_coffee_vend_01",
			"p_lestersbed_s",
			"p_lev_sofa_s",
			"p_med_jet_01_s",
			"p_mbbed_s",
			"p_new_j_counter_03",
			"p_oil_pjack_02_s",
			"p_oil_pjack_03_s",
			"p_tram_crash_s",
			"p_v_med_p_sofa_s",
			"p_v_res_tt_bed_s",
			"prop_barrel_pile_01",
			"prop_air_generator_03",
			"prop_air_sechut_01",
			"prop_aircon_l_01",
			"prop_aircon_m_10",
			"prop_aircon_tna_02",
			"prop_asteroid_01",
			"prop_barier_conc_05c",
			"prop_barrel_pile_01",
			"prop_bbq_3",
			"prop_bench_03",
			"prop_bh1_09_mp_gar",
			"prop_big_cin_screen",
			"prop_biolab_g_door",
			"prop_bleachers_05_cr",
			"prop_bmu_02_ld",
			"prop_box_wood04a",
			"prop_boxpile_02b",
			"prop_boxpile_07a",
			"prop_bumper_04",
			"prop_bush_lrg_01e_cr2",
			"prop_bush_lrg_01c_cr",
			"prop_busstop_04",
			"prop_byard_dingy",
			"prop_byard_floatpile",
			"prop_byard_rowboat1",
			"prop_cablespool_03",
			"prop_car_battery_01",
			"prop_cash_crate_01",
			"prop_cctv_unit_01",
			"prop_cementbags01",
			"prop_ch2_05d_g_door",
			"prop_cleaning_trolly",
			"prop_coffin_01",
			"prop_coffin_02b",
			"prop_com_gar_door_01",
			"prop_com_ls_door_01",
			"prop_flag_canada",
			"prop_flag_eu",
			"prop_flag_france",
			"prop_flag_german",
			"prop_flag_ireland",
			"prop_flag_japan",
			"prop_flag_ls",
			"prop_flag_lsfd",
			"prop_flag_lsservices",
			"prop_flag_mexico",
			"prop_flag_russia",
			"prop_flag_sa",
			"prop_flag_sapd",
			"prop_flag_scotland",
			"prop_flag_sheriff",
			"prop_flag_uk",
			"prop_flag_us",
			"prop_golfflag",
			"ap1_lod_slod4",
			"po1_lod_slod4",
			"ch3_lod_11b13_slod3",
			"ch3_lod_101114b_slod3",
			"vb_lod_slod4",
			"ch1_lod_slod3a",
			"ch1_lod_slod3c",
			"cs3_lod_1_slod3",
			"cs2_lod_06_slod3",
			"cs1_lod2_01_7_slod3",
			"dt1_lod_f1_slod3",
			"sp1_lod_slod4",
			"sm_lod_slod3",
			"bh1_lod_slod3",
			"hw1_lod_slod4",
			"id1_lod_slod4",
			"sc1_lod_slod4",
			"dt1_21_reflproxy",
			"cs4_lod_01_slod3",
			"cs3_lod_2_slod3",
			"cs5_lod_1_4_slod3",
			"ch3_lod_6_10_slod3",
			"cs6_lod_slod3_04",
			"cs6_lod_slod2_05",
			"cs6_lod_slod2_03",
			"cs1_lod3_terrain_slod3_01",
			"cs1_lod3_terrain_slod3_06",
			"cs2_lod_1234_slod3",
			"cs2_29_slod1",
			"xm_mpchristmasadditions_hatch_10",
			"cs1_14b_railbg01_d2",
			"cs1_14b_decal_007",
			"cs1_12_b01_d",
			"cs2_06c_lk_slod_01",
			"apa_mp_apa_yacht_win",
			"cs1_roadsa06_d",
			"hei_cs3_07_mil_decals07",
			"cs3_07_hanger04_lod",
			"dt1_11_slod1",
			"dt1_props_combo0110_slod",
			"dt1_21_slod",
			"dt1_02_slod",
			"dt1_05_lod",
			"dt1_03_build2top_lod",
			"ss1_11_slod",
			"sc1_06_carpark_lod",
			"sc1_08_det_04",
			"sc1_08_hdg1",
			"dt1_06_hospsignem",
			"cs2_29_biolab127",
			"xm_prop_x17_osphatch_27m",
			"cs1_10_cablebld_d",
			"dt1_06_hospsignem",
			"dt1_19_lspd02_lod",
			"dt1_06_g1_detail",
			"dt1_rd1_r5h_slod1",
			"dt1_16_build006_decals",
			"dt1_18_build5_lod",
			"id2_rd_lod",
			"po1_03_brig2_noshad",
			"po1_03_brig2_noshad",
			"po1_sh1_sunk_lod",
			"cs1_07_sea_plane_13",
			"cs1_09_sea_ufo",
			"prop_mp_spike_01",
			"prop_tyre_spike_01", 
			"prop_container_ld2", 
			"lts_prop_lts_ramp_03", 
			"prop_jetski_ramp_01",
			"prop_mp_ramp_03_tu",
			"prop_skate_flatramp_cr",
			"stt_prop_ramp_adj_loop",
			"stt_prop_ramp_multi_loop_rb",
			"stt_prop_ramp_spiral_l", 
			"stt_prop_ramp_spiral_l_m", 
			"prop_const_fence03b_cr", 
			"prop_const_fence02b", 
			"prop_const_fence03a_cr",
			"prop_fnc_farm_01e",
			"prop_fnccorgm_02c",
			"ch3_01_dino", 
			"p_pallet_02a_s", 
			"prop_conc_blocks01a", 
			"prop_consign_01a", 
			"prop_mb_cargo_04b", 
			"prop_mb_crate_01a_set",
			"prop_pipe_stack_01", 
			"prop_roadcone01c", 
			"prop_rub_cage01b", 
			"prop_sign_road_01a",
			"prop_sign_road_03m", 
			"prop_traffic_rail_2",
			"prop_traffic_rail_1a",
			"prop_traffic_03a", 
			"prop_traffic_01d", 
			"prop_skid_trolley_1", 
			"hei_prop_yah_seat_03",
			"lts_prop_lts_elecbox_24", 
			"lts_prop_lts_elecbox_24b",
			"p_airdancer_01_s", 
			"p_amb_brolly_01",
			"p_amb_brolly_01_s", 
			"p_dumpster_t", 
			"p_ld_coffee_vend_01",
			"p_patio_lounger1_s", 
			"prop_air_bagloader2_cr",
			"prop_air_bigradar", 
			"prop_air_blastfence_01",
			"prop_air_stair_01", 
			"prop_air_sechut_01",
			"prop_airport_sale_sign",

	},
	BlacklistedVehicleCreating = {
			--VEHICLES
			"skylift",
			"valkyrie2",
			"airbus",
			"hunter",
			"bus",
			"armytanker",
			"armytrailer",
			"armytrailer2",
			"baletrailer",
			"cablecar",
			"docktrailer",
			"freighttrailer",
			"graintrailer",
			"proptrailer",
			"raketrailer",
			"tr2",
			"tug",
			"tr3",
			"tr4",
			"trflat",
			"tvtrailer",
			"tanker",
			"tanker2",
			"trailerlarge",
			"trailerlogs",
			"trailersmall",
			"trailers",
			"trailers2",
			"trailers3",
			"trailers4",
			--'RHINO',
			'AKULA',
			'SAVAGE',
			'HUNTER',
			--'BUZZARD',
			'BUZZARD2',
			'ANNIHILATOR',
			'VALKYRIE',
			'HYDRA',
			'APC',
			'Trailersmall2',
			'Lazer',
			'oppressor',
			'mogul',
			'barrage',
			'Khanjali',
			'volatol',
			'chernobog',
			'avenger',
			'stromberg',
			'nightshark',
			'besra',
			'babushka ',
			'starling',
			'insurgent',
			'cargobob',
			'cargobob2',
			'cargobob3',
			'cargobob4',
			'caracara',
			'deluxo',
			'menacer',
			'scramjet',
			'oppressor2',
			'revolter',
			'viseris',
			'savestra',
			'thruster',
			'ardent',
			'dune3',
			'tampa3',
			'halftrack',
			'nokota',
			'strikeforce',
			'bombushka',
			'molotok',
			'pyro',
			'ruiner2',
			'limo2',
			'technical',
			'technical2',
			'technical3',
			'jb700w',
			'blazer5',
			'insurgent3',
			'boxville5',
			'bruiser',
			'bruiser2',
			'bruiser3',
			'brutus',
			'brutus2',
			'brutus3',
			'cerberus',
			'cerberus2',
			'cerberus3',
			'dominator4',
			'dominator5',
			'dominator6',
			'impaler2',
			'impaler3',
			'impaler4',
			'imperator',
			'imperator2',
			'imperator3',
			'issi4',
			'issi5',
			'issi6',
			'monster3',
			'monster4',
			'monster5',
			'scarab',
			'scarab2',
			'scarab3',
			'slamvan4',
			'slamvan5',
			'slamvan6',
			'zr380',
			'zr3802',
			'zr3803',
			'alphaz1',
			'avenger2',
			'blimp',
			'blimp2',
			'blimp3',
			'cargoplane',
			'cuban800',
			'dodo',
			'duster',
			'howard',
			'jet',
			'luxor',
			'luxor2',
			'mammatus',
			'microlight',
			'miljet',
			'nimbus',
			'rogue',
			'seabreeze',
			'shamal',
			'stunt',
			'titan',
			'tula',
			'velum',
			'velum2',
			'vestra',
			'dump',
			'rumpo',
			'Tipper',
			'DockHandler',
			'Dozer',
			'Dump',
			'Mixer',
			'Rubble',
			'Tipper',
			'Burrito1',
			'Burrito2',
			'benson',
			'benson',
			'cerberus',
			'cerberus2',
			'cerberus3',
			'hauler',
			'hauler2',
			'mule',
			'mule2',
			'mule3',
			'mule4',
			'packer',
			'phantom',
			'phantom2',
			'phantom3',
			'pounder',
			'pounder2',
			'stockade'
	},

	BlacklistedPedsCreating = {
			-- PEDS
			"a_m_m_acult_01",
			"s_m_y_swat_01",
			"a_m_o_acult_01",
			"ig_wade",
			"s_m_y_hwaycop_01",
			"A_M_Y_ACult_01",
			's_m_m_movalien_01',
			's_m_m_movallien_01',
			'u_m_y_babyd',
			'CS_Orleans',
			'A_M_Y_ACult_01',
			'S_M_M_MovSpace_01',
			'U_M_Y_Zombie_01',
			's_m_y_blackops_01',
			'a_f_y_topless_01',
			"s_f_y_bartender_01",
			"a_m_y_beachvesp_01",
			"a_m_y_beach_03",
			"a_m_y_beach_02",
			"a_m_m_beach_02",
			"a_m_y_beach_01",
			"s_m_y_baywatch_01",
			"mp_f_boatstaff_01",
			"u_m_m_bikehire_01", 
			"a_f_y_bevhills_04",
			"s_m_m_bouncer_01",
			"s_m_y_armymech_01", 
			"s_m_y_autopsy_01",
			"s_m_y_blackops_01",
			"s_m_y_blackops_02"
	},

	BlacklistWord = {
		"test", "word", "cheat", "executor"
	},
}

